config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'lists#index'

  resources :lists do
    resources :bookmarks
  end
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @list = List.find(params[:list_id])

  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    bookmark = Bookmark.new(bookmark_create_params)
    bookmark.list = @list
    if bookmark.save
      redirect_to list_path(@list)
    else
      render json: ErrorSerializer.serialize(user.errors), status: :unprocessable_entity
    end
  end

  def edit
  end

  private

  def bookmark_create_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])


  end

  def new
    @list = List.new
  end

  def create
    list = List.new(list_create_params)
    if list.save
      redirect_to list_path(list)
    else
      render json: ErrorSerializer.serialize(user.errors), status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_create_params)
    @list.save
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_create_params
    params.require(:list).permit(:name, :body, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to list_path(:list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>Bookmarks#index</h1>
<p>Find me in app/views/bookmarks/index.html.erb</p>

app/views/bookmarks/new.html.erb
<ul class="nav justify-content-center mb-3">
  <div class="nav-item">
    <%= link_to "My lists", lists_path, :class => "nav-link active" %>
  </div>
  <div class="nav-item">
    <%= link_to "New list", new_list_path(@list), :class => "nav-link active" %>
  </div>
</ul>

<h1>Add movie</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="col m-3 text-center" >
<h1>Add list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
   <%= f.input :photo, as: :file %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<ul class="nav justify-content-center mb-3">
  <div class="nav-item">
    <%= link_to "My lists", lists_path, :class => "nav-link active" %>
  </div>
  <div class="nav-item">
    <%= link_to "New list", new_list_path(@list), :class => "nav-link active" %>
  </div>
</ul>

<div class="position-relative overflow-hidden p-md-5 text-center bg-light bannerimage grayscale image">
    <div class="col-md-5 p-lg-12 mx-auto my-5">
      <h3>Save any kinds of movies</h3>
    </div>
  </div>


<div class="list">
    <h3>My lists</h3>
    <div> </div>
    <div class="add-list"> <%= link_to "Create a movie list", new_list_path(@list), :class => "btn btn-success" %></div>
  </div>

<div class="list">
 <% @lists.each do |list| %>
<div class="card">
  <div class="grayscale">
  <%= cl_image_tag list.photo.key, height: 150, width: 220, crop: :fill %>
  </div>
  <div class="card-img-overlay d-flex">
    <h5 class="align-self-center mx-auto list-title"><%= link_to list.name, list_path(list) %></h5>
  </div>
</div>
    <% end %>
</div>

app/views/lists/new.html.erb
<div class="col m-3 text-center" >
<h1>Add list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
   <%= f.input :photo, as: :file %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<ul class="nav justify-content-center mb-3">
  <div class="nav-item">
    <%= link_to "My lists", lists_path, :class => "nav-link active" %>
  </div>
  <div class="nav-item">
    <%= link_to "New list", new_list_path(@list), :class => "nav-link active" %>
  </div>
</ul>

<div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')"
>
  <%= @list.name %>
</div>

<div class="list">
    <h3><%= @list.movies.count %> bookmarks</h3>
    <div> </div>
    <div class="add-list"> <%= link_to "Add a movie", new_list_bookmark_path(@list, @bookmark), :class => "btn btn-success" %>
     <%= link_to "Delete list", list_path(@list), :class => "btn btn-success", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
  </div>

<div class="list-container">
  <% @list.movies.each do |movie| %>
    <div class="card">
      <img src="https://image.tmdb.org/t/p/w500/<%= movie.poster_url %>" class="card-img-top image" alt="...">
      <div class="card-content">
        <h5 class="card-title"><%= movie.title %>・<%= movie.rating %><i class="fa-sharp fa-solid fa-star star"></i></h5>
        <p class="card-text max-lines"><%= movie.overview %></p>
      </div>
      <div class="card-bottom">
      <p class="card-comment"><i class="fa-sharp fa-solid fa-quote-left"></i><strong><em> <%= Bookmark.find_by(movie_id: movie.id).comment %></strong></em></p>
        <%= link_to "delete", movie_path(movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>